-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity feedforward_matmul_xnor is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_4_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_5_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_6_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_7_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_8_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_9_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_10_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_11_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_12_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_13_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_14_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_15_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_16_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_17_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_18_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_19_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_20_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_21_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_22_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_23_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_24_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_25_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_26_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_27_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_28_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_29_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_30_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_31_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_32_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_33_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_34_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_35_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_36_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_37_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_38_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_39_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_40_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_41_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_42_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_43_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_44_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_45_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_46_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_47_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_48_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_49_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_50_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_51_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_52_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_53_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_54_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_55_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_56_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_57_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_58_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_59_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_60_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_61_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_62_val : IN STD_LOGIC_VECTOR (31 downto 0);
    A_63_val : IN STD_LOGIC_VECTOR (31 downto 0);
    res_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    res_ce0 : OUT STD_LOGIC;
    res_we0 : OUT STD_LOGIC;
    res_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of feedforward_matmul_xnor is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln61_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal x_1_reg_1863 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_1_reg_1863_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_4_fu_1245_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_4_reg_1872 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_7_fu_1271_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_7_reg_1877 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_11_fu_1297_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_11_reg_1882 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_14_fu_1323_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_14_reg_1887 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_19_fu_1349_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_19_reg_1892 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_22_fu_1375_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_22_reg_1897 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_26_fu_1401_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_26_reg_1902 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_29_fu_1427_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_29_reg_1907 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_35_fu_1453_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_35_reg_1912 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_38_fu_1479_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_38_reg_1917 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_42_fu_1505_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_42_reg_1922 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_45_fu_1531_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_45_reg_1927 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_50_fu_1557_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_50_reg_1932 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_53_fu_1583_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_53_reg_1937 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_57_fu_1609_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_57_reg_1942 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_60_fu_1635_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_60_reg_1947 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln64_fu_1834_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln64_reg_1952 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln61_fu_1840_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_fu_164 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln61_fu_579_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal res_we0_local : STD_LOGIC;
    signal zext_ln62_fu_1851_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_ce0_local : STD_LOGIC;
    signal icmp_ln21_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_1_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_9_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_44_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_53_fu_903_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_42_fu_837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_49_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_24_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_59_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_46_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_10_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_40_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_52_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_27_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_37_fu_807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_4_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_17_fu_687_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_21_fu_711_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_23_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_48_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_16_fu_681_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_18_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_51_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_43_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_14_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_41_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_55_fu_915_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_25_fu_735_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_2_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_33_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_32_fu_777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_50_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_34_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_54_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_29_fu_759_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_62_fu_957_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_63_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_20_fu_705_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_61_fu_951_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_36_fu_801_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_60_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_28_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_8_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_12_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_7_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_58_fu_933_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_6_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_57_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_26_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_15_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_56_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_38_fu_813_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_11_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_45_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_19_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_3_fu_603_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_47_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_31_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_13_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_39_fu_819_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_30_fu_765_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_35_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_22_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_5_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln21_1_cast_fu_973_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_cast_fu_969_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_2_fu_1225_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_9_cast_fu_977_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_44_cast_fu_981_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_3_fu_1235_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_2_fu_1241_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_1_fu_1231_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_53_cast_fu_985_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_42_cast_fu_989_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_5_fu_1251_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_49_cast_fu_993_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_24_cast_fu_997_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_6_fu_1261_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_5_fu_1267_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_4_fu_1257_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_59_cast_fu_1001_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_46_cast_fu_1005_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_9_fu_1277_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_10_cast_fu_1009_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_40_cast_fu_1013_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_10_fu_1287_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_9_fu_1293_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_8_fu_1283_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_52_cast_fu_1017_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_27_cast_fu_1021_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_12_fu_1303_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_37_cast_fu_1025_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_4_cast_fu_1029_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_13_fu_1313_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_12_fu_1319_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_11_fu_1309_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_17_cast_fu_1033_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_21_cast_fu_1037_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_17_fu_1329_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_23_cast_fu_1041_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_48_cast_fu_1045_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_18_fu_1339_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_17_fu_1345_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_16_fu_1335_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_16_cast_fu_1049_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_18_cast_fu_1053_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_20_fu_1355_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_51_cast_fu_1057_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_43_cast_fu_1061_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_21_fu_1365_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_20_fu_1371_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_19_fu_1361_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_14_cast_fu_1065_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_41_cast_fu_1069_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_24_fu_1381_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_55_cast_fu_1073_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_25_cast_fu_1077_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_25_fu_1391_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_24_fu_1397_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_23_fu_1387_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_2_cast_fu_1081_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_33_cast_fu_1085_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_27_fu_1407_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_32_cast_fu_1089_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_50_cast_fu_1093_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_28_fu_1417_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_27_fu_1423_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_26_fu_1413_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_34_cast_fu_1097_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_54_cast_fu_1101_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_33_fu_1433_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_29_cast_fu_1105_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_62_cast_fu_1109_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_34_fu_1443_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_33_fu_1449_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_32_fu_1439_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_63_cast_fu_1113_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_20_cast_fu_1117_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_36_fu_1459_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_61_cast_fu_1121_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_36_cast_fu_1125_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_37_fu_1469_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_36_fu_1475_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_35_fu_1465_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_60_cast_fu_1129_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_28_cast_fu_1133_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_40_fu_1485_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_8_cast_fu_1137_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_12_cast_fu_1141_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_41_fu_1495_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_40_fu_1501_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_39_fu_1491_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_7_cast_fu_1145_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_58_cast_fu_1149_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_43_fu_1511_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_6_cast_fu_1153_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_57_cast_fu_1157_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_44_fu_1521_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_43_fu_1527_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_42_fu_1517_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_26_cast_fu_1161_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_15_cast_fu_1165_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_48_fu_1537_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_56_cast_fu_1169_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_38_cast_fu_1173_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_49_fu_1547_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_48_fu_1553_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_47_fu_1543_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_11_cast_fu_1177_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_45_cast_fu_1181_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_51_fu_1563_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_19_cast_fu_1185_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_3_cast_fu_1189_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_52_fu_1573_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_51_fu_1579_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_50_fu_1569_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_47_cast_fu_1193_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_31_cast_fu_1197_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_55_fu_1589_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_13_cast_fu_1201_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_39_cast_fu_1205_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_56_fu_1599_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_55_fu_1605_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_54_fu_1595_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln21_30_cast_fu_1209_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_35_cast_fu_1213_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_58_fu_1615_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln21_22_cast_fu_1217_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_fu_1221_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln64_59_fu_1625_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln64_58_fu_1631_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_57_fu_1621_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln64_6_fu_1649_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_3_fu_1646_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_8_fu_1652_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_13_fu_1665_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_10_fu_1662_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_15_fu_1668_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_14_fu_1674_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_7_fu_1658_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln64_16_fu_1678_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_21_fu_1691_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_18_fu_1688_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_23_fu_1694_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_28_fu_1707_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_25_fu_1704_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_30_fu_1710_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_29_fu_1716_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_22_fu_1700_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln64_31_fu_1720_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_30_fu_1726_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln64_15_fu_1684_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln64_32_fu_1730_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln64_37_fu_1743_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_34_fu_1740_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_39_fu_1746_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_44_fu_1759_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_41_fu_1756_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_46_fu_1762_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_45_fu_1768_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_38_fu_1752_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln64_47_fu_1772_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_52_fu_1785_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_49_fu_1782_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_54_fu_1788_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_59_fu_1801_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_56_fu_1798_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln64_61_fu_1804_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln64_60_fu_1810_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_53_fu_1794_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln64_62_fu_1814_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln64_61_fu_1820_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln64_46_fu_1778_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln64_63_fu_1824_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln64_62_fu_1830_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln64_31_fu_1736_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal cnt_fu_1844_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component feedforward_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component feedforward_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    x_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln61_fu_573_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_164 <= add_ln61_fu_579_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_164 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln64_11_reg_1882 <= add_ln64_11_fu_1297_p2;
                add_ln64_14_reg_1887 <= add_ln64_14_fu_1323_p2;
                add_ln64_19_reg_1892 <= add_ln64_19_fu_1349_p2;
                add_ln64_22_reg_1897 <= add_ln64_22_fu_1375_p2;
                add_ln64_26_reg_1902 <= add_ln64_26_fu_1401_p2;
                add_ln64_29_reg_1907 <= add_ln64_29_fu_1427_p2;
                add_ln64_35_reg_1912 <= add_ln64_35_fu_1453_p2;
                add_ln64_38_reg_1917 <= add_ln64_38_fu_1479_p2;
                add_ln64_42_reg_1922 <= add_ln64_42_fu_1505_p2;
                add_ln64_45_reg_1927 <= add_ln64_45_fu_1531_p2;
                add_ln64_4_reg_1872 <= add_ln64_4_fu_1245_p2;
                add_ln64_50_reg_1932 <= add_ln64_50_fu_1557_p2;
                add_ln64_53_reg_1937 <= add_ln64_53_fu_1583_p2;
                add_ln64_57_reg_1942 <= add_ln64_57_fu_1609_p2;
                add_ln64_60_reg_1947 <= add_ln64_60_fu_1635_p2;
                add_ln64_7_reg_1877 <= add_ln64_7_fu_1271_p2;
                add_ln64_reg_1952 <= add_ln64_fu_1834_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                x_1_reg_1863 <= ap_sig_allocacmp_x_1;
                x_1_reg_1863_pp0_iter1_reg <= x_1_reg_1863;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln61_fu_579_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv4_1));
    add_ln64_10_fu_1287_p2 <= std_logic_vector(unsigned(icmp_ln21_10_cast_fu_1009_p1) + unsigned(icmp_ln21_40_cast_fu_1013_p1));
    add_ln64_11_fu_1297_p2 <= std_logic_vector(unsigned(zext_ln64_9_fu_1293_p1) + unsigned(zext_ln64_8_fu_1283_p1));
    add_ln64_12_fu_1303_p2 <= std_logic_vector(unsigned(icmp_ln21_52_cast_fu_1017_p1) + unsigned(icmp_ln21_27_cast_fu_1021_p1));
    add_ln64_13_fu_1313_p2 <= std_logic_vector(unsigned(icmp_ln21_37_cast_fu_1025_p1) + unsigned(icmp_ln21_4_cast_fu_1029_p1));
    add_ln64_14_fu_1323_p2 <= std_logic_vector(unsigned(zext_ln64_12_fu_1319_p1) + unsigned(zext_ln64_11_fu_1309_p1));
    add_ln64_15_fu_1668_p2 <= std_logic_vector(unsigned(zext_ln64_13_fu_1665_p1) + unsigned(zext_ln64_10_fu_1662_p1));
    add_ln64_16_fu_1678_p2 <= std_logic_vector(unsigned(zext_ln64_14_fu_1674_p1) + unsigned(zext_ln64_7_fu_1658_p1));
    add_ln64_17_fu_1329_p2 <= std_logic_vector(unsigned(icmp_ln21_17_cast_fu_1033_p1) + unsigned(icmp_ln21_21_cast_fu_1037_p1));
    add_ln64_18_fu_1339_p2 <= std_logic_vector(unsigned(icmp_ln21_23_cast_fu_1041_p1) + unsigned(icmp_ln21_48_cast_fu_1045_p1));
    add_ln64_19_fu_1349_p2 <= std_logic_vector(unsigned(zext_ln64_17_fu_1345_p1) + unsigned(zext_ln64_16_fu_1335_p1));
    add_ln64_20_fu_1355_p2 <= std_logic_vector(unsigned(icmp_ln21_16_cast_fu_1049_p1) + unsigned(icmp_ln21_18_cast_fu_1053_p1));
    add_ln64_21_fu_1365_p2 <= std_logic_vector(unsigned(icmp_ln21_51_cast_fu_1057_p1) + unsigned(icmp_ln21_43_cast_fu_1061_p1));
    add_ln64_22_fu_1375_p2 <= std_logic_vector(unsigned(zext_ln64_20_fu_1371_p1) + unsigned(zext_ln64_19_fu_1361_p1));
    add_ln64_23_fu_1694_p2 <= std_logic_vector(unsigned(zext_ln64_21_fu_1691_p1) + unsigned(zext_ln64_18_fu_1688_p1));
    add_ln64_24_fu_1381_p2 <= std_logic_vector(unsigned(icmp_ln21_14_cast_fu_1065_p1) + unsigned(icmp_ln21_41_cast_fu_1069_p1));
    add_ln64_25_fu_1391_p2 <= std_logic_vector(unsigned(icmp_ln21_55_cast_fu_1073_p1) + unsigned(icmp_ln21_25_cast_fu_1077_p1));
    add_ln64_26_fu_1401_p2 <= std_logic_vector(unsigned(zext_ln64_24_fu_1397_p1) + unsigned(zext_ln64_23_fu_1387_p1));
    add_ln64_27_fu_1407_p2 <= std_logic_vector(unsigned(icmp_ln21_2_cast_fu_1081_p1) + unsigned(icmp_ln21_33_cast_fu_1085_p1));
    add_ln64_28_fu_1417_p2 <= std_logic_vector(unsigned(icmp_ln21_32_cast_fu_1089_p1) + unsigned(icmp_ln21_50_cast_fu_1093_p1));
    add_ln64_29_fu_1427_p2 <= std_logic_vector(unsigned(zext_ln64_27_fu_1423_p1) + unsigned(zext_ln64_26_fu_1413_p1));
    add_ln64_2_fu_1225_p2 <= std_logic_vector(unsigned(icmp_ln21_1_cast_fu_973_p1) + unsigned(icmp_ln21_cast_fu_969_p1));
    add_ln64_30_fu_1710_p2 <= std_logic_vector(unsigned(zext_ln64_28_fu_1707_p1) + unsigned(zext_ln64_25_fu_1704_p1));
    add_ln64_31_fu_1720_p2 <= std_logic_vector(unsigned(zext_ln64_29_fu_1716_p1) + unsigned(zext_ln64_22_fu_1700_p1));
    add_ln64_32_fu_1730_p2 <= std_logic_vector(unsigned(zext_ln64_30_fu_1726_p1) + unsigned(zext_ln64_15_fu_1684_p1));
    add_ln64_33_fu_1433_p2 <= std_logic_vector(unsigned(icmp_ln21_34_cast_fu_1097_p1) + unsigned(icmp_ln21_54_cast_fu_1101_p1));
    add_ln64_34_fu_1443_p2 <= std_logic_vector(unsigned(icmp_ln21_29_cast_fu_1105_p1) + unsigned(icmp_ln21_62_cast_fu_1109_p1));
    add_ln64_35_fu_1453_p2 <= std_logic_vector(unsigned(zext_ln64_33_fu_1449_p1) + unsigned(zext_ln64_32_fu_1439_p1));
    add_ln64_36_fu_1459_p2 <= std_logic_vector(unsigned(icmp_ln21_63_cast_fu_1113_p1) + unsigned(icmp_ln21_20_cast_fu_1117_p1));
    add_ln64_37_fu_1469_p2 <= std_logic_vector(unsigned(icmp_ln21_61_cast_fu_1121_p1) + unsigned(icmp_ln21_36_cast_fu_1125_p1));
    add_ln64_38_fu_1479_p2 <= std_logic_vector(unsigned(zext_ln64_36_fu_1475_p1) + unsigned(zext_ln64_35_fu_1465_p1));
    add_ln64_39_fu_1746_p2 <= std_logic_vector(unsigned(zext_ln64_37_fu_1743_p1) + unsigned(zext_ln64_34_fu_1740_p1));
    add_ln64_3_fu_1235_p2 <= std_logic_vector(unsigned(icmp_ln21_9_cast_fu_977_p1) + unsigned(icmp_ln21_44_cast_fu_981_p1));
    add_ln64_40_fu_1485_p2 <= std_logic_vector(unsigned(icmp_ln21_60_cast_fu_1129_p1) + unsigned(icmp_ln21_28_cast_fu_1133_p1));
    add_ln64_41_fu_1495_p2 <= std_logic_vector(unsigned(icmp_ln21_8_cast_fu_1137_p1) + unsigned(icmp_ln21_12_cast_fu_1141_p1));
    add_ln64_42_fu_1505_p2 <= std_logic_vector(unsigned(zext_ln64_40_fu_1501_p1) + unsigned(zext_ln64_39_fu_1491_p1));
    add_ln64_43_fu_1511_p2 <= std_logic_vector(unsigned(icmp_ln21_7_cast_fu_1145_p1) + unsigned(icmp_ln21_58_cast_fu_1149_p1));
    add_ln64_44_fu_1521_p2 <= std_logic_vector(unsigned(icmp_ln21_6_cast_fu_1153_p1) + unsigned(icmp_ln21_57_cast_fu_1157_p1));
    add_ln64_45_fu_1531_p2 <= std_logic_vector(unsigned(zext_ln64_43_fu_1527_p1) + unsigned(zext_ln64_42_fu_1517_p1));
    add_ln64_46_fu_1762_p2 <= std_logic_vector(unsigned(zext_ln64_44_fu_1759_p1) + unsigned(zext_ln64_41_fu_1756_p1));
    add_ln64_47_fu_1772_p2 <= std_logic_vector(unsigned(zext_ln64_45_fu_1768_p1) + unsigned(zext_ln64_38_fu_1752_p1));
    add_ln64_48_fu_1537_p2 <= std_logic_vector(unsigned(icmp_ln21_26_cast_fu_1161_p1) + unsigned(icmp_ln21_15_cast_fu_1165_p1));
    add_ln64_49_fu_1547_p2 <= std_logic_vector(unsigned(icmp_ln21_56_cast_fu_1169_p1) + unsigned(icmp_ln21_38_cast_fu_1173_p1));
    add_ln64_4_fu_1245_p2 <= std_logic_vector(unsigned(zext_ln64_2_fu_1241_p1) + unsigned(zext_ln64_1_fu_1231_p1));
    add_ln64_50_fu_1557_p2 <= std_logic_vector(unsigned(zext_ln64_48_fu_1553_p1) + unsigned(zext_ln64_47_fu_1543_p1));
    add_ln64_51_fu_1563_p2 <= std_logic_vector(unsigned(icmp_ln21_11_cast_fu_1177_p1) + unsigned(icmp_ln21_45_cast_fu_1181_p1));
    add_ln64_52_fu_1573_p2 <= std_logic_vector(unsigned(icmp_ln21_19_cast_fu_1185_p1) + unsigned(icmp_ln21_3_cast_fu_1189_p1));
    add_ln64_53_fu_1583_p2 <= std_logic_vector(unsigned(zext_ln64_51_fu_1579_p1) + unsigned(zext_ln64_50_fu_1569_p1));
    add_ln64_54_fu_1788_p2 <= std_logic_vector(unsigned(zext_ln64_52_fu_1785_p1) + unsigned(zext_ln64_49_fu_1782_p1));
    add_ln64_55_fu_1589_p2 <= std_logic_vector(unsigned(icmp_ln21_47_cast_fu_1193_p1) + unsigned(icmp_ln21_31_cast_fu_1197_p1));
    add_ln64_56_fu_1599_p2 <= std_logic_vector(unsigned(icmp_ln21_13_cast_fu_1201_p1) + unsigned(icmp_ln21_39_cast_fu_1205_p1));
    add_ln64_57_fu_1609_p2 <= std_logic_vector(unsigned(zext_ln64_55_fu_1605_p1) + unsigned(zext_ln64_54_fu_1595_p1));
    add_ln64_58_fu_1615_p2 <= std_logic_vector(unsigned(icmp_ln21_30_cast_fu_1209_p1) + unsigned(icmp_ln21_35_cast_fu_1213_p1));
    add_ln64_59_fu_1625_p2 <= std_logic_vector(unsigned(icmp_ln21_22_cast_fu_1217_p1) + unsigned(zext_ln64_fu_1221_p1));
    add_ln64_5_fu_1251_p2 <= std_logic_vector(unsigned(icmp_ln21_53_cast_fu_985_p1) + unsigned(icmp_ln21_42_cast_fu_989_p1));
    add_ln64_60_fu_1635_p2 <= std_logic_vector(unsigned(zext_ln64_58_fu_1631_p1) + unsigned(zext_ln64_57_fu_1621_p1));
    add_ln64_61_fu_1804_p2 <= std_logic_vector(unsigned(zext_ln64_59_fu_1801_p1) + unsigned(zext_ln64_56_fu_1798_p1));
    add_ln64_62_fu_1814_p2 <= std_logic_vector(unsigned(zext_ln64_60_fu_1810_p1) + unsigned(zext_ln64_53_fu_1794_p1));
    add_ln64_63_fu_1824_p2 <= std_logic_vector(unsigned(zext_ln64_61_fu_1820_p1) + unsigned(zext_ln64_46_fu_1778_p1));
    add_ln64_6_fu_1261_p2 <= std_logic_vector(unsigned(icmp_ln21_49_cast_fu_993_p1) + unsigned(icmp_ln21_24_cast_fu_997_p1));
    add_ln64_7_fu_1271_p2 <= std_logic_vector(unsigned(zext_ln64_5_fu_1267_p1) + unsigned(zext_ln64_4_fu_1257_p1));
    add_ln64_8_fu_1652_p2 <= std_logic_vector(unsigned(zext_ln64_6_fu_1649_p1) + unsigned(zext_ln64_3_fu_1646_p1));
    add_ln64_9_fu_1277_p2 <= std_logic_vector(unsigned(icmp_ln21_59_cast_fu_1001_p1) + unsigned(icmp_ln21_46_cast_fu_1005_p1));
    add_ln64_fu_1834_p2 <= std_logic_vector(unsigned(zext_ln64_62_fu_1830_p1) + unsigned(zext_ln64_31_fu_1736_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln61_fu_573_p2)
    begin
        if (((icmp_ln61_fu_573_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_164, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_164;
        end if; 
    end process;

    cnt_fu_1844_p3 <= (add_ln64_reg_1952 & ap_const_lv8_0);
    icmp_ln21_10_cast_fu_1009_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_10_fu_645_p2),2));
    icmp_ln21_10_fu_645_p2 <= "1" when (A_10_val = ap_const_lv32_100) else "0";
    icmp_ln21_11_cast_fu_1177_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_11_fu_651_p2),2));
    icmp_ln21_11_fu_651_p2 <= "1" when (A_11_val = ap_const_lv32_0) else "0";
    icmp_ln21_12_cast_fu_1141_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_12_fu_657_p2),2));
    icmp_ln21_12_fu_657_p2 <= "1" when (A_12_val = ap_const_lv32_0) else "0";
    icmp_ln21_13_cast_fu_1201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_13_fu_663_p2),2));
    icmp_ln21_13_fu_663_p2 <= "1" when (A_13_val = ap_const_lv32_0) else "0";
    icmp_ln21_14_cast_fu_1065_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_14_fu_669_p2),2));
    icmp_ln21_14_fu_669_p2 <= "1" when (A_14_val = ap_const_lv32_100) else "0";
    icmp_ln21_15_cast_fu_1165_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_15_fu_675_p2),2));
    icmp_ln21_15_fu_675_p2 <= "1" when (A_15_val = ap_const_lv32_0) else "0";
    icmp_ln21_16_cast_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_16_fu_681_p2),2));
    icmp_ln21_16_fu_681_p2 <= "1" when (A_16_val = ap_const_lv32_100) else "0";
    icmp_ln21_17_cast_fu_1033_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_17_fu_687_p2),2));
    icmp_ln21_17_fu_687_p2 <= "1" when (A_17_val = ap_const_lv32_100) else "0";
    icmp_ln21_18_cast_fu_1053_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_18_fu_693_p2),2));
    icmp_ln21_18_fu_693_p2 <= "1" when (A_18_val = ap_const_lv32_100) else "0";
    icmp_ln21_19_cast_fu_1185_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_19_fu_699_p2),2));
    icmp_ln21_19_fu_699_p2 <= "1" when (A_19_val = ap_const_lv32_0) else "0";
    icmp_ln21_1_cast_fu_973_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_1_fu_591_p2),2));
    icmp_ln21_1_fu_591_p2 <= "1" when (A_1_val = ap_const_lv32_100) else "0";
    icmp_ln21_20_cast_fu_1117_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_20_fu_705_p2),2));
    icmp_ln21_20_fu_705_p2 <= "1" when (A_20_val = ap_const_lv32_0) else "0";
    icmp_ln21_21_cast_fu_1037_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_21_fu_711_p2),2));
    icmp_ln21_21_fu_711_p2 <= "1" when (A_21_val = ap_const_lv32_100) else "0";
    icmp_ln21_22_cast_fu_1217_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_22_fu_717_p2),2));
    icmp_ln21_22_fu_717_p2 <= "1" when (A_22_val = ap_const_lv32_0) else "0";
    icmp_ln21_23_cast_fu_1041_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_23_fu_723_p2),2));
    icmp_ln21_23_fu_723_p2 <= "1" when (A_23_val = ap_const_lv32_100) else "0";
    icmp_ln21_24_cast_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_24_fu_729_p2),2));
    icmp_ln21_24_fu_729_p2 <= "1" when (A_24_val = ap_const_lv32_100) else "0";
    icmp_ln21_25_cast_fu_1077_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_25_fu_735_p2),2));
    icmp_ln21_25_fu_735_p2 <= "1" when (A_25_val = ap_const_lv32_100) else "0";
    icmp_ln21_26_cast_fu_1161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_26_fu_741_p2),2));
    icmp_ln21_26_fu_741_p2 <= "1" when (A_26_val = ap_const_lv32_0) else "0";
    icmp_ln21_27_cast_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_27_fu_747_p2),2));
    icmp_ln21_27_fu_747_p2 <= "1" when (A_27_val = ap_const_lv32_100) else "0";
    icmp_ln21_28_cast_fu_1133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_28_fu_753_p2),2));
    icmp_ln21_28_fu_753_p2 <= "1" when (A_28_val = ap_const_lv32_0) else "0";
    icmp_ln21_29_cast_fu_1105_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_29_fu_759_p2),2));
    icmp_ln21_29_fu_759_p2 <= "1" when (A_29_val = ap_const_lv32_100) else "0";
    icmp_ln21_2_cast_fu_1081_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_2_fu_597_p2),2));
    icmp_ln21_2_fu_597_p2 <= "1" when (A_2_val = ap_const_lv32_100) else "0";
    icmp_ln21_30_cast_fu_1209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_30_fu_765_p2),2));
    icmp_ln21_30_fu_765_p2 <= "1" when (A_30_val = ap_const_lv32_0) else "0";
    icmp_ln21_31_cast_fu_1197_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_31_fu_771_p2),2));
    icmp_ln21_31_fu_771_p2 <= "1" when (A_31_val = ap_const_lv32_0) else "0";
    icmp_ln21_32_cast_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_32_fu_777_p2),2));
    icmp_ln21_32_fu_777_p2 <= "1" when (A_32_val = ap_const_lv32_100) else "0";
    icmp_ln21_33_cast_fu_1085_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_33_fu_783_p2),2));
    icmp_ln21_33_fu_783_p2 <= "1" when (A_33_val = ap_const_lv32_100) else "0";
    icmp_ln21_34_cast_fu_1097_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_34_fu_789_p2),2));
    icmp_ln21_34_fu_789_p2 <= "1" when (A_34_val = ap_const_lv32_100) else "0";
    icmp_ln21_35_cast_fu_1213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_35_fu_795_p2),2));
    icmp_ln21_35_fu_795_p2 <= "1" when (A_35_val = ap_const_lv32_0) else "0";
    icmp_ln21_36_cast_fu_1125_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_36_fu_801_p2),2));
    icmp_ln21_36_fu_801_p2 <= "1" when (A_36_val = ap_const_lv32_0) else "0";
    icmp_ln21_37_cast_fu_1025_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_37_fu_807_p2),2));
    icmp_ln21_37_fu_807_p2 <= "1" when (A_37_val = ap_const_lv32_100) else "0";
    icmp_ln21_38_cast_fu_1173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_38_fu_813_p2),2));
    icmp_ln21_38_fu_813_p2 <= "1" when (A_38_val = ap_const_lv32_0) else "0";
    icmp_ln21_39_cast_fu_1205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_39_fu_819_p2),2));
    icmp_ln21_39_fu_819_p2 <= "1" when (A_39_val = ap_const_lv32_0) else "0";
    icmp_ln21_3_cast_fu_1189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_3_fu_603_p2),2));
    icmp_ln21_3_fu_603_p2 <= "1" when (A_3_val = ap_const_lv32_0) else "0";
    icmp_ln21_40_cast_fu_1013_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_40_fu_825_p2),2));
    icmp_ln21_40_fu_825_p2 <= "1" when (A_40_val = ap_const_lv32_100) else "0";
    icmp_ln21_41_cast_fu_1069_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_41_fu_831_p2),2));
    icmp_ln21_41_fu_831_p2 <= "1" when (A_41_val = ap_const_lv32_100) else "0";
    icmp_ln21_42_cast_fu_989_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_42_fu_837_p2),2));
    icmp_ln21_42_fu_837_p2 <= "1" when (A_42_val = ap_const_lv32_100) else "0";
    icmp_ln21_43_cast_fu_1061_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_43_fu_843_p2),2));
    icmp_ln21_43_fu_843_p2 <= "1" when (A_43_val = ap_const_lv32_100) else "0";
    icmp_ln21_44_cast_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_44_fu_849_p2),2));
    icmp_ln21_44_fu_849_p2 <= "1" when (A_44_val = ap_const_lv32_100) else "0";
    icmp_ln21_45_cast_fu_1181_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_45_fu_855_p2),2));
    icmp_ln21_45_fu_855_p2 <= "1" when (A_45_val = ap_const_lv32_0) else "0";
    icmp_ln21_46_cast_fu_1005_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_46_fu_861_p2),2));
    icmp_ln21_46_fu_861_p2 <= "1" when (A_46_val = ap_const_lv32_100) else "0";
    icmp_ln21_47_cast_fu_1193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_47_fu_867_p2),2));
    icmp_ln21_47_fu_867_p2 <= "1" when (A_47_val = ap_const_lv32_0) else "0";
    icmp_ln21_48_cast_fu_1045_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_48_fu_873_p2),2));
    icmp_ln21_48_fu_873_p2 <= "1" when (A_48_val = ap_const_lv32_100) else "0";
    icmp_ln21_49_cast_fu_993_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_49_fu_879_p2),2));
    icmp_ln21_49_fu_879_p2 <= "1" when (A_49_val = ap_const_lv32_100) else "0";
    icmp_ln21_4_cast_fu_1029_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_4_fu_609_p2),2));
    icmp_ln21_4_fu_609_p2 <= "1" when (A_4_val = ap_const_lv32_100) else "0";
    icmp_ln21_50_cast_fu_1093_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_50_fu_885_p2),2));
    icmp_ln21_50_fu_885_p2 <= "1" when (A_50_val = ap_const_lv32_100) else "0";
    icmp_ln21_51_cast_fu_1057_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_51_fu_891_p2),2));
    icmp_ln21_51_fu_891_p2 <= "1" when (A_51_val = ap_const_lv32_100) else "0";
    icmp_ln21_52_cast_fu_1017_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_52_fu_897_p2),2));
    icmp_ln21_52_fu_897_p2 <= "1" when (A_52_val = ap_const_lv32_100) else "0";
    icmp_ln21_53_cast_fu_985_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_53_fu_903_p2),2));
    icmp_ln21_53_fu_903_p2 <= "1" when (A_53_val = ap_const_lv32_100) else "0";
    icmp_ln21_54_cast_fu_1101_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_54_fu_909_p2),2));
    icmp_ln21_54_fu_909_p2 <= "1" when (A_54_val = ap_const_lv32_100) else "0";
    icmp_ln21_55_cast_fu_1073_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_55_fu_915_p2),2));
    icmp_ln21_55_fu_915_p2 <= "1" when (A_55_val = ap_const_lv32_100) else "0";
    icmp_ln21_56_cast_fu_1169_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_56_fu_921_p2),2));
    icmp_ln21_56_fu_921_p2 <= "1" when (A_56_val = ap_const_lv32_0) else "0";
    icmp_ln21_57_cast_fu_1157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_57_fu_927_p2),2));
    icmp_ln21_57_fu_927_p2 <= "1" when (A_57_val = ap_const_lv32_0) else "0";
    icmp_ln21_58_cast_fu_1149_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_58_fu_933_p2),2));
    icmp_ln21_58_fu_933_p2 <= "1" when (A_58_val = ap_const_lv32_0) else "0";
    icmp_ln21_59_cast_fu_1001_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_59_fu_939_p2),2));
    icmp_ln21_59_fu_939_p2 <= "1" when (A_59_val = ap_const_lv32_100) else "0";
    icmp_ln21_5_fu_615_p2 <= "1" when (A_5_val = ap_const_lv32_0) else "0";
    icmp_ln21_60_cast_fu_1129_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_60_fu_945_p2),2));
    icmp_ln21_60_fu_945_p2 <= "1" when (A_60_val = ap_const_lv32_0) else "0";
    icmp_ln21_61_cast_fu_1121_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_61_fu_951_p2),2));
    icmp_ln21_61_fu_951_p2 <= "1" when (A_61_val = ap_const_lv32_0) else "0";
    icmp_ln21_62_cast_fu_1109_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_62_fu_957_p2),2));
    icmp_ln21_62_fu_957_p2 <= "1" when (A_62_val = ap_const_lv32_0) else "0";
    icmp_ln21_63_cast_fu_1113_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_63_fu_963_p2),2));
    icmp_ln21_63_fu_963_p2 <= "1" when (A_63_val = ap_const_lv32_0) else "0";
    icmp_ln21_6_cast_fu_1153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_6_fu_621_p2),2));
    icmp_ln21_6_fu_621_p2 <= "1" when (A_6_val = ap_const_lv32_0) else "0";
    icmp_ln21_7_cast_fu_1145_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_7_fu_627_p2),2));
    icmp_ln21_7_fu_627_p2 <= "1" when (A_7_val = ap_const_lv32_0) else "0";
    icmp_ln21_8_cast_fu_1137_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_8_fu_633_p2),2));
    icmp_ln21_8_fu_633_p2 <= "1" when (A_8_val = ap_const_lv32_0) else "0";
    icmp_ln21_9_cast_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_9_fu_639_p2),2));
    icmp_ln21_9_fu_639_p2 <= "1" when (A_9_val = ap_const_lv32_100) else "0";
    icmp_ln21_cast_fu_969_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_fu_585_p2),2));
    icmp_ln21_fu_585_p2 <= "1" when (A_0_val = ap_const_lv32_100) else "0";
    icmp_ln61_fu_573_p2 <= "1" when (ap_sig_allocacmp_x_1 = ap_const_lv4_A) else "0";
    res_address0 <= zext_ln61_fu_1840_p1(4 - 1 downto 0);
    res_ce0 <= res_ce0_local;

    res_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            res_ce0_local <= ap_const_logic_1;
        else 
            res_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    res_d0 <= zext_ln62_fu_1851_p1;
    res_we0 <= res_we0_local;

    res_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            res_we0_local <= ap_const_logic_1;
        else 
            res_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln61_fu_1840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(x_1_reg_1863_pp0_iter1_reg),64));
    zext_ln62_fu_1851_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cnt_fu_1844_p3),32));
    zext_ln64_10_fu_1662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_11_reg_1882),4));
    zext_ln64_11_fu_1309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_12_fu_1303_p2),3));
    zext_ln64_12_fu_1319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_13_fu_1313_p2),3));
    zext_ln64_13_fu_1665_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_14_reg_1887),4));
    zext_ln64_14_fu_1674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_15_fu_1668_p2),5));
    zext_ln64_15_fu_1684_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_16_fu_1678_p2),6));
    zext_ln64_16_fu_1335_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_17_fu_1329_p2),3));
    zext_ln64_17_fu_1345_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_18_fu_1339_p2),3));
    zext_ln64_18_fu_1688_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_19_reg_1892),4));
    zext_ln64_19_fu_1361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_20_fu_1355_p2),3));
    zext_ln64_1_fu_1231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_2_fu_1225_p2),3));
    zext_ln64_20_fu_1371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_21_fu_1365_p2),3));
    zext_ln64_21_fu_1691_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_22_reg_1897),4));
    zext_ln64_22_fu_1700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_23_fu_1694_p2),5));
    zext_ln64_23_fu_1387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_24_fu_1381_p2),3));
    zext_ln64_24_fu_1397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_25_fu_1391_p2),3));
    zext_ln64_25_fu_1704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_26_reg_1902),4));
    zext_ln64_26_fu_1413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_27_fu_1407_p2),3));
    zext_ln64_27_fu_1423_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_28_fu_1417_p2),3));
    zext_ln64_28_fu_1707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_29_reg_1907),4));
    zext_ln64_29_fu_1716_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_30_fu_1710_p2),5));
    zext_ln64_2_fu_1241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_3_fu_1235_p2),3));
    zext_ln64_30_fu_1726_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_31_fu_1720_p2),6));
    zext_ln64_31_fu_1736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_32_fu_1730_p2),7));
    zext_ln64_32_fu_1439_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_33_fu_1433_p2),3));
    zext_ln64_33_fu_1449_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_34_fu_1443_p2),3));
    zext_ln64_34_fu_1740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_35_reg_1912),4));
    zext_ln64_35_fu_1465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_36_fu_1459_p2),3));
    zext_ln64_36_fu_1475_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_37_fu_1469_p2),3));
    zext_ln64_37_fu_1743_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_38_reg_1917),4));
    zext_ln64_38_fu_1752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_39_fu_1746_p2),5));
    zext_ln64_39_fu_1491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_40_fu_1485_p2),3));
    zext_ln64_3_fu_1646_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_4_reg_1872),4));
    zext_ln64_40_fu_1501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_41_fu_1495_p2),3));
    zext_ln64_41_fu_1756_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_42_reg_1922),4));
    zext_ln64_42_fu_1517_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_43_fu_1511_p2),3));
    zext_ln64_43_fu_1527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_44_fu_1521_p2),3));
    zext_ln64_44_fu_1759_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_45_reg_1927),4));
    zext_ln64_45_fu_1768_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_46_fu_1762_p2),5));
    zext_ln64_46_fu_1778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_47_fu_1772_p2),6));
    zext_ln64_47_fu_1543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_48_fu_1537_p2),3));
    zext_ln64_48_fu_1553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_49_fu_1547_p2),3));
    zext_ln64_49_fu_1782_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_50_reg_1932),4));
    zext_ln64_4_fu_1257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_5_fu_1251_p2),3));
    zext_ln64_50_fu_1569_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_51_fu_1563_p2),3));
    zext_ln64_51_fu_1579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_52_fu_1573_p2),3));
    zext_ln64_52_fu_1785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_53_reg_1937),4));
    zext_ln64_53_fu_1794_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_54_fu_1788_p2),5));
    zext_ln64_54_fu_1595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_55_fu_1589_p2),3));
    zext_ln64_55_fu_1605_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_56_fu_1599_p2),3));
    zext_ln64_56_fu_1798_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_57_reg_1942),4));
    zext_ln64_57_fu_1621_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_58_fu_1615_p2),3));
    zext_ln64_58_fu_1631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_59_fu_1625_p2),3));
    zext_ln64_59_fu_1801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_60_reg_1947),4));
    zext_ln64_5_fu_1267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_6_fu_1261_p2),3));
    zext_ln64_60_fu_1810_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_61_fu_1804_p2),5));
    zext_ln64_61_fu_1820_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_62_fu_1814_p2),6));
    zext_ln64_62_fu_1830_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_63_fu_1824_p2),7));
    zext_ln64_6_fu_1649_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_7_reg_1877),4));
    zext_ln64_7_fu_1658_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_8_fu_1652_p2),5));
    zext_ln64_8_fu_1283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_9_fu_1277_p2),3));
    zext_ln64_9_fu_1293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln64_10_fu_1287_p2),3));
    zext_ln64_fu_1221_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln21_5_fu_615_p2),2));
end behav;
