

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer1_activations_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer1_activations_2_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer2_activations_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer2_activations_4_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer2_activations_5_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer2_activations_6_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.layer3_activations_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_103_1_fu_6376"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_103_1_fu_6376.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_113_2_fu_6646"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_113_2_fu_6646.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_126_3_fu_6654"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_126_3_fu_6654.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_141_5_fu_6789"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_141_5_fu_6789.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_147_6_fu_6799"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_147_6_fu_6799.sparsemux_9_2_32_1_1_U403"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_147_6_fu_6799.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_156_7_fu_6936"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_156_7_fu_6936.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_163_8_fu_6943"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_feedforward_Pipeline_VITIS_LOOP_163_8_fu_6943.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_513_8_32_1_1_U548"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_257_7_32_1_1_U549"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_257_7_32_1_1_U550"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_data_V_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_keep_V_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_strb_V_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_input_stream_V_last_V_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_data_V_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_keep_V_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_strb_V_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_output_stream_V_last_V_U"}]}
set DependenceCheckSize 0
