// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module feedforward_feedforward_Pipeline_VITIS_LOOP_153_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer2_activations_address0,
        layer2_activations_ce0,
        layer2_activations_q0,
        layer2_activations_1_address0,
        layer2_activations_1_ce0,
        layer2_activations_1_q0,
        layer2_activations_2_address0,
        layer2_activations_2_ce0,
        layer2_activations_2_q0,
        layer2_activations_3_address0,
        layer2_activations_3_ce0,
        layer2_activations_3_q0,
        shl_i_i_i_i653127_out,
        shl_i_i_i_i653127_out_ap_vld,
        shl_i_i_i_i653125_out,
        shl_i_i_i_i653125_out_ap_vld,
        shl_i_i_i_i653123_out,
        shl_i_i_i_i653123_out_ap_vld,
        shl_i_i_i_i653121_out,
        shl_i_i_i_i653121_out_ap_vld,
        shl_i_i_i_i653119_out,
        shl_i_i_i_i653119_out_ap_vld,
        shl_i_i_i_i653117_out,
        shl_i_i_i_i653117_out_ap_vld,
        shl_i_i_i_i653115_out,
        shl_i_i_i_i653115_out_ap_vld,
        shl_i_i_i_i653113_out,
        shl_i_i_i_i653113_out_ap_vld,
        shl_i_i_i_i653111_out,
        shl_i_i_i_i653111_out_ap_vld,
        shl_i_i_i_i653109_out,
        shl_i_i_i_i653109_out_ap_vld,
        shl_i_i_i_i653107_out,
        shl_i_i_i_i653107_out_ap_vld,
        shl_i_i_i_i653105_out,
        shl_i_i_i_i653105_out_ap_vld,
        shl_i_i_i_i653103_out,
        shl_i_i_i_i653103_out_ap_vld,
        shl_i_i_i_i653101_out,
        shl_i_i_i_i653101_out_ap_vld,
        shl_i_i_i_i65399_out,
        shl_i_i_i_i65399_out_ap_vld,
        shl_i_i_i_i65397_out,
        shl_i_i_i_i65397_out_ap_vld,
        shl_i_i_i_i65395_out,
        shl_i_i_i_i65395_out_ap_vld,
        shl_i_i_i_i65393_out,
        shl_i_i_i_i65393_out_ap_vld,
        shl_i_i_i_i65391_out,
        shl_i_i_i_i65391_out_ap_vld,
        shl_i_i_i_i65389_out,
        shl_i_i_i_i65389_out_ap_vld,
        shl_i_i_i_i65387_out,
        shl_i_i_i_i65387_out_ap_vld,
        shl_i_i_i_i65385_out,
        shl_i_i_i_i65385_out_ap_vld,
        shl_i_i_i_i65383_out,
        shl_i_i_i_i65383_out_ap_vld,
        shl_i_i_i_i65381_out,
        shl_i_i_i_i65381_out_ap_vld,
        shl_i_i_i_i65379_out,
        shl_i_i_i_i65379_out_ap_vld,
        shl_i_i_i_i65377_out,
        shl_i_i_i_i65377_out_ap_vld,
        shl_i_i_i_i65375_out,
        shl_i_i_i_i65375_out_ap_vld,
        shl_i_i_i_i65373_out,
        shl_i_i_i_i65373_out_ap_vld,
        shl_i_i_i_i65371_out,
        shl_i_i_i_i65371_out_ap_vld,
        shl_i_i_i_i65369_out,
        shl_i_i_i_i65369_out_ap_vld,
        shl_i_i_i_i65367_out,
        shl_i_i_i_i65367_out_ap_vld,
        shl_i_i_i_i65365_out,
        shl_i_i_i_i65365_out_ap_vld,
        shl_i_i_i_i65363_out,
        shl_i_i_i_i65363_out_ap_vld,
        shl_i_i_i_i65361_out,
        shl_i_i_i_i65361_out_ap_vld,
        shl_i_i_i_i65359_out,
        shl_i_i_i_i65359_out_ap_vld,
        shl_i_i_i_i65357_out,
        shl_i_i_i_i65357_out_ap_vld,
        shl_i_i_i_i65355_out,
        shl_i_i_i_i65355_out_ap_vld,
        shl_i_i_i_i65353_out,
        shl_i_i_i_i65353_out_ap_vld,
        shl_i_i_i_i65351_out,
        shl_i_i_i_i65351_out_ap_vld,
        shl_i_i_i_i65349_out,
        shl_i_i_i_i65349_out_ap_vld,
        shl_i_i_i_i65347_out,
        shl_i_i_i_i65347_out_ap_vld,
        shl_i_i_i_i65345_out,
        shl_i_i_i_i65345_out_ap_vld,
        shl_i_i_i_i65343_out,
        shl_i_i_i_i65343_out_ap_vld,
        shl_i_i_i_i65341_out,
        shl_i_i_i_i65341_out_ap_vld,
        shl_i_i_i_i65339_out,
        shl_i_i_i_i65339_out_ap_vld,
        shl_i_i_i_i65337_out,
        shl_i_i_i_i65337_out_ap_vld,
        shl_i_i_i_i65335_out,
        shl_i_i_i_i65335_out_ap_vld,
        shl_i_i_i_i65333_out,
        shl_i_i_i_i65333_out_ap_vld,
        shl_i_i_i_i65331_out,
        shl_i_i_i_i65331_out_ap_vld,
        shl_i_i_i_i65329_out,
        shl_i_i_i_i65329_out_ap_vld,
        shl_i_i_i_i65327_out,
        shl_i_i_i_i65327_out_ap_vld,
        shl_i_i_i_i65325_out,
        shl_i_i_i_i65325_out_ap_vld,
        shl_i_i_i_i65323_out,
        shl_i_i_i_i65323_out_ap_vld,
        shl_i_i_i_i65321_out,
        shl_i_i_i_i65321_out_ap_vld,
        shl_i_i_i_i65319_out,
        shl_i_i_i_i65319_out_ap_vld,
        shl_i_i_i_i65317_out,
        shl_i_i_i_i65317_out_ap_vld,
        shl_i_i_i_i65315_out,
        shl_i_i_i_i65315_out_ap_vld,
        shl_i_i_i_i65313_out,
        shl_i_i_i_i65313_out_ap_vld,
        shl_i_i_i_i65311_out,
        shl_i_i_i_i65311_out_ap_vld,
        shl_i_i_i_i6539_out,
        shl_i_i_i_i6539_out_ap_vld,
        shl_i_i_i_i6537_out,
        shl_i_i_i_i6537_out_ap_vld,
        shl_i_i_i_i6535_out,
        shl_i_i_i_i6535_out_ap_vld,
        shl_i_i_i_i6533_out,
        shl_i_i_i_i6533_out_ap_vld,
        shl_i_i_i_i6531_out,
        shl_i_i_i_i6531_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] layer2_activations_address0;
output   layer2_activations_ce0;
input  [31:0] layer2_activations_q0;
output  [3:0] layer2_activations_1_address0;
output   layer2_activations_1_ce0;
input  [31:0] layer2_activations_1_q0;
output  [3:0] layer2_activations_2_address0;
output   layer2_activations_2_ce0;
input  [31:0] layer2_activations_2_q0;
output  [3:0] layer2_activations_3_address0;
output   layer2_activations_3_ce0;
input  [31:0] layer2_activations_3_q0;
output  [31:0] shl_i_i_i_i653127_out;
output   shl_i_i_i_i653127_out_ap_vld;
output  [31:0] shl_i_i_i_i653125_out;
output   shl_i_i_i_i653125_out_ap_vld;
output  [31:0] shl_i_i_i_i653123_out;
output   shl_i_i_i_i653123_out_ap_vld;
output  [31:0] shl_i_i_i_i653121_out;
output   shl_i_i_i_i653121_out_ap_vld;
output  [31:0] shl_i_i_i_i653119_out;
output   shl_i_i_i_i653119_out_ap_vld;
output  [31:0] shl_i_i_i_i653117_out;
output   shl_i_i_i_i653117_out_ap_vld;
output  [31:0] shl_i_i_i_i653115_out;
output   shl_i_i_i_i653115_out_ap_vld;
output  [31:0] shl_i_i_i_i653113_out;
output   shl_i_i_i_i653113_out_ap_vld;
output  [31:0] shl_i_i_i_i653111_out;
output   shl_i_i_i_i653111_out_ap_vld;
output  [31:0] shl_i_i_i_i653109_out;
output   shl_i_i_i_i653109_out_ap_vld;
output  [31:0] shl_i_i_i_i653107_out;
output   shl_i_i_i_i653107_out_ap_vld;
output  [31:0] shl_i_i_i_i653105_out;
output   shl_i_i_i_i653105_out_ap_vld;
output  [31:0] shl_i_i_i_i653103_out;
output   shl_i_i_i_i653103_out_ap_vld;
output  [31:0] shl_i_i_i_i653101_out;
output   shl_i_i_i_i653101_out_ap_vld;
output  [31:0] shl_i_i_i_i65399_out;
output   shl_i_i_i_i65399_out_ap_vld;
output  [31:0] shl_i_i_i_i65397_out;
output   shl_i_i_i_i65397_out_ap_vld;
output  [31:0] shl_i_i_i_i65395_out;
output   shl_i_i_i_i65395_out_ap_vld;
output  [31:0] shl_i_i_i_i65393_out;
output   shl_i_i_i_i65393_out_ap_vld;
output  [31:0] shl_i_i_i_i65391_out;
output   shl_i_i_i_i65391_out_ap_vld;
output  [31:0] shl_i_i_i_i65389_out;
output   shl_i_i_i_i65389_out_ap_vld;
output  [31:0] shl_i_i_i_i65387_out;
output   shl_i_i_i_i65387_out_ap_vld;
output  [31:0] shl_i_i_i_i65385_out;
output   shl_i_i_i_i65385_out_ap_vld;
output  [31:0] shl_i_i_i_i65383_out;
output   shl_i_i_i_i65383_out_ap_vld;
output  [31:0] shl_i_i_i_i65381_out;
output   shl_i_i_i_i65381_out_ap_vld;
output  [31:0] shl_i_i_i_i65379_out;
output   shl_i_i_i_i65379_out_ap_vld;
output  [31:0] shl_i_i_i_i65377_out;
output   shl_i_i_i_i65377_out_ap_vld;
output  [31:0] shl_i_i_i_i65375_out;
output   shl_i_i_i_i65375_out_ap_vld;
output  [31:0] shl_i_i_i_i65373_out;
output   shl_i_i_i_i65373_out_ap_vld;
output  [31:0] shl_i_i_i_i65371_out;
output   shl_i_i_i_i65371_out_ap_vld;
output  [31:0] shl_i_i_i_i65369_out;
output   shl_i_i_i_i65369_out_ap_vld;
output  [31:0] shl_i_i_i_i65367_out;
output   shl_i_i_i_i65367_out_ap_vld;
output  [31:0] shl_i_i_i_i65365_out;
output   shl_i_i_i_i65365_out_ap_vld;
output  [31:0] shl_i_i_i_i65363_out;
output   shl_i_i_i_i65363_out_ap_vld;
output  [31:0] shl_i_i_i_i65361_out;
output   shl_i_i_i_i65361_out_ap_vld;
output  [31:0] shl_i_i_i_i65359_out;
output   shl_i_i_i_i65359_out_ap_vld;
output  [31:0] shl_i_i_i_i65357_out;
output   shl_i_i_i_i65357_out_ap_vld;
output  [31:0] shl_i_i_i_i65355_out;
output   shl_i_i_i_i65355_out_ap_vld;
output  [31:0] shl_i_i_i_i65353_out;
output   shl_i_i_i_i65353_out_ap_vld;
output  [31:0] shl_i_i_i_i65351_out;
output   shl_i_i_i_i65351_out_ap_vld;
output  [31:0] shl_i_i_i_i65349_out;
output   shl_i_i_i_i65349_out_ap_vld;
output  [31:0] shl_i_i_i_i65347_out;
output   shl_i_i_i_i65347_out_ap_vld;
output  [31:0] shl_i_i_i_i65345_out;
output   shl_i_i_i_i65345_out_ap_vld;
output  [31:0] shl_i_i_i_i65343_out;
output   shl_i_i_i_i65343_out_ap_vld;
output  [31:0] shl_i_i_i_i65341_out;
output   shl_i_i_i_i65341_out_ap_vld;
output  [31:0] shl_i_i_i_i65339_out;
output   shl_i_i_i_i65339_out_ap_vld;
output  [31:0] shl_i_i_i_i65337_out;
output   shl_i_i_i_i65337_out_ap_vld;
output  [31:0] shl_i_i_i_i65335_out;
output   shl_i_i_i_i65335_out_ap_vld;
output  [31:0] shl_i_i_i_i65333_out;
output   shl_i_i_i_i65333_out_ap_vld;
output  [31:0] shl_i_i_i_i65331_out;
output   shl_i_i_i_i65331_out_ap_vld;
output  [31:0] shl_i_i_i_i65329_out;
output   shl_i_i_i_i65329_out_ap_vld;
output  [31:0] shl_i_i_i_i65327_out;
output   shl_i_i_i_i65327_out_ap_vld;
output  [31:0] shl_i_i_i_i65325_out;
output   shl_i_i_i_i65325_out_ap_vld;
output  [31:0] shl_i_i_i_i65323_out;
output   shl_i_i_i_i65323_out_ap_vld;
output  [31:0] shl_i_i_i_i65321_out;
output   shl_i_i_i_i65321_out_ap_vld;
output  [31:0] shl_i_i_i_i65319_out;
output   shl_i_i_i_i65319_out_ap_vld;
output  [31:0] shl_i_i_i_i65317_out;
output   shl_i_i_i_i65317_out_ap_vld;
output  [31:0] shl_i_i_i_i65315_out;
output   shl_i_i_i_i65315_out_ap_vld;
output  [31:0] shl_i_i_i_i65313_out;
output   shl_i_i_i_i65313_out_ap_vld;
output  [31:0] shl_i_i_i_i65311_out;
output   shl_i_i_i_i65311_out_ap_vld;
output  [31:0] shl_i_i_i_i6539_out;
output   shl_i_i_i_i6539_out_ap_vld;
output  [31:0] shl_i_i_i_i6537_out;
output   shl_i_i_i_i6537_out_ap_vld;
output  [31:0] shl_i_i_i_i6535_out;
output   shl_i_i_i_i6535_out_ap_vld;
output  [31:0] shl_i_i_i_i6533_out;
output   shl_i_i_i_i6533_out_ap_vld;
output  [31:0] shl_i_i_i_i6531_out;
output   shl_i_i_i_i6531_out_ap_vld;

reg ap_idle;
reg shl_i_i_i_i653127_out_ap_vld;
reg shl_i_i_i_i653125_out_ap_vld;
reg shl_i_i_i_i653123_out_ap_vld;
reg shl_i_i_i_i653121_out_ap_vld;
reg shl_i_i_i_i653119_out_ap_vld;
reg shl_i_i_i_i653117_out_ap_vld;
reg shl_i_i_i_i653115_out_ap_vld;
reg shl_i_i_i_i653113_out_ap_vld;
reg shl_i_i_i_i653111_out_ap_vld;
reg shl_i_i_i_i653109_out_ap_vld;
reg shl_i_i_i_i653107_out_ap_vld;
reg shl_i_i_i_i653105_out_ap_vld;
reg shl_i_i_i_i653103_out_ap_vld;
reg shl_i_i_i_i653101_out_ap_vld;
reg shl_i_i_i_i65399_out_ap_vld;
reg shl_i_i_i_i65397_out_ap_vld;
reg shl_i_i_i_i65395_out_ap_vld;
reg shl_i_i_i_i65393_out_ap_vld;
reg shl_i_i_i_i65391_out_ap_vld;
reg shl_i_i_i_i65389_out_ap_vld;
reg shl_i_i_i_i65387_out_ap_vld;
reg shl_i_i_i_i65385_out_ap_vld;
reg shl_i_i_i_i65383_out_ap_vld;
reg shl_i_i_i_i65381_out_ap_vld;
reg shl_i_i_i_i65379_out_ap_vld;
reg shl_i_i_i_i65377_out_ap_vld;
reg shl_i_i_i_i65375_out_ap_vld;
reg shl_i_i_i_i65373_out_ap_vld;
reg shl_i_i_i_i65371_out_ap_vld;
reg shl_i_i_i_i65369_out_ap_vld;
reg shl_i_i_i_i65367_out_ap_vld;
reg shl_i_i_i_i65365_out_ap_vld;
reg shl_i_i_i_i65363_out_ap_vld;
reg shl_i_i_i_i65361_out_ap_vld;
reg shl_i_i_i_i65359_out_ap_vld;
reg shl_i_i_i_i65357_out_ap_vld;
reg shl_i_i_i_i65355_out_ap_vld;
reg shl_i_i_i_i65353_out_ap_vld;
reg shl_i_i_i_i65351_out_ap_vld;
reg shl_i_i_i_i65349_out_ap_vld;
reg shl_i_i_i_i65347_out_ap_vld;
reg shl_i_i_i_i65345_out_ap_vld;
reg shl_i_i_i_i65343_out_ap_vld;
reg shl_i_i_i_i65341_out_ap_vld;
reg shl_i_i_i_i65339_out_ap_vld;
reg shl_i_i_i_i65337_out_ap_vld;
reg shl_i_i_i_i65335_out_ap_vld;
reg shl_i_i_i_i65333_out_ap_vld;
reg shl_i_i_i_i65331_out_ap_vld;
reg shl_i_i_i_i65329_out_ap_vld;
reg shl_i_i_i_i65327_out_ap_vld;
reg shl_i_i_i_i65325_out_ap_vld;
reg shl_i_i_i_i65323_out_ap_vld;
reg shl_i_i_i_i65321_out_ap_vld;
reg shl_i_i_i_i65319_out_ap_vld;
reg shl_i_i_i_i65317_out_ap_vld;
reg shl_i_i_i_i65315_out_ap_vld;
reg shl_i_i_i_i65313_out_ap_vld;
reg shl_i_i_i_i65311_out_ap_vld;
reg shl_i_i_i_i6539_out_ap_vld;
reg shl_i_i_i_i6537_out_ap_vld;
reg shl_i_i_i_i6535_out_ap_vld;
reg shl_i_i_i_i6533_out_ap_vld;
reg shl_i_i_i_i6531_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln153_fu_1078_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln153_reg_2124;
wire   [1:0] trunc_ln153_fu_1090_p1;
reg   [1:0] trunc_ln153_reg_2128;
wire   [5:0] trunc_ln153_1_fu_1094_p1;
reg   [5:0] trunc_ln153_1_reg_2133;
wire   [0:0] icmp_ln41_fu_1144_p2;
reg   [0:0] icmp_ln41_reg_2157;
wire   [63:0] zext_ln153_fu_1108_p1;
wire    ap_block_pp0_stage0;
reg   [6:0] i_fu_310;
wire   [6:0] add_ln153_fu_1084_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_3;
reg   [31:0] shl_i_i_i_i6531_fu_314;
wire   [31:0] select_ln156_fu_1150_p3;
reg    ap_predicate_pred439_state3;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [31:0] shl_i_i_i_i6533_fu_318;
reg    ap_predicate_pred454_state3;
reg   [31:0] shl_i_i_i_i6535_fu_322;
reg    ap_predicate_pred463_state3;
reg   [31:0] shl_i_i_i_i6537_fu_326;
reg    ap_predicate_pred472_state3;
reg   [31:0] shl_i_i_i_i6539_fu_330;
reg    ap_predicate_pred481_state3;
reg   [31:0] shl_i_i_i_i65311_fu_334;
reg    ap_predicate_pred490_state3;
reg   [31:0] shl_i_i_i_i65313_fu_338;
reg    ap_predicate_pred499_state3;
reg   [31:0] shl_i_i_i_i65315_fu_342;
reg    ap_predicate_pred508_state3;
reg   [31:0] shl_i_i_i_i65317_fu_346;
reg    ap_predicate_pred517_state3;
reg   [31:0] shl_i_i_i_i65319_fu_350;
reg    ap_predicate_pred526_state3;
reg   [31:0] shl_i_i_i_i65321_fu_354;
reg    ap_predicate_pred535_state3;
reg   [31:0] shl_i_i_i_i65323_fu_358;
reg    ap_predicate_pred544_state3;
reg   [31:0] shl_i_i_i_i65325_fu_362;
reg    ap_predicate_pred553_state3;
reg   [31:0] shl_i_i_i_i65327_fu_366;
reg    ap_predicate_pred562_state3;
reg   [31:0] shl_i_i_i_i65329_fu_370;
reg    ap_predicate_pred571_state3;
reg   [31:0] shl_i_i_i_i65331_fu_374;
reg    ap_predicate_pred580_state3;
reg   [31:0] shl_i_i_i_i65333_fu_378;
reg    ap_predicate_pred589_state3;
reg   [31:0] shl_i_i_i_i65335_fu_382;
reg    ap_predicate_pred598_state3;
reg   [31:0] shl_i_i_i_i65337_fu_386;
reg    ap_predicate_pred607_state3;
reg   [31:0] shl_i_i_i_i65339_fu_390;
reg    ap_predicate_pred616_state3;
reg   [31:0] shl_i_i_i_i65341_fu_394;
reg    ap_predicate_pred625_state3;
reg   [31:0] shl_i_i_i_i65343_fu_398;
reg    ap_predicate_pred634_state3;
reg   [31:0] shl_i_i_i_i65345_fu_402;
reg    ap_predicate_pred643_state3;
reg   [31:0] shl_i_i_i_i65347_fu_406;
reg    ap_predicate_pred652_state3;
reg   [31:0] shl_i_i_i_i65349_fu_410;
reg    ap_predicate_pred661_state3;
reg   [31:0] shl_i_i_i_i65351_fu_414;
reg    ap_predicate_pred670_state3;
reg   [31:0] shl_i_i_i_i65353_fu_418;
reg    ap_predicate_pred679_state3;
reg   [31:0] shl_i_i_i_i65355_fu_422;
reg    ap_predicate_pred688_state3;
reg   [31:0] shl_i_i_i_i65357_fu_426;
reg    ap_predicate_pred697_state3;
reg   [31:0] shl_i_i_i_i65359_fu_430;
reg    ap_predicate_pred706_state3;
reg   [31:0] shl_i_i_i_i65361_fu_434;
reg    ap_predicate_pred715_state3;
reg   [31:0] shl_i_i_i_i65363_fu_438;
reg    ap_predicate_pred724_state3;
reg   [31:0] shl_i_i_i_i65365_fu_442;
reg    ap_predicate_pred733_state3;
reg   [31:0] shl_i_i_i_i65367_fu_446;
reg    ap_predicate_pred742_state3;
reg   [31:0] shl_i_i_i_i65369_fu_450;
reg    ap_predicate_pred751_state3;
reg   [31:0] shl_i_i_i_i65371_fu_454;
reg    ap_predicate_pred760_state3;
reg   [31:0] shl_i_i_i_i65373_fu_458;
reg    ap_predicate_pred769_state3;
reg   [31:0] shl_i_i_i_i65375_fu_462;
reg    ap_predicate_pred778_state3;
reg   [31:0] shl_i_i_i_i65377_fu_466;
reg    ap_predicate_pred787_state3;
reg   [31:0] shl_i_i_i_i65379_fu_470;
reg    ap_predicate_pred796_state3;
reg   [31:0] shl_i_i_i_i65381_fu_474;
reg    ap_predicate_pred805_state3;
reg   [31:0] shl_i_i_i_i65383_fu_478;
reg    ap_predicate_pred814_state3;
reg   [31:0] shl_i_i_i_i65385_fu_482;
reg    ap_predicate_pred823_state3;
reg   [31:0] shl_i_i_i_i65387_fu_486;
reg    ap_predicate_pred832_state3;
reg   [31:0] shl_i_i_i_i65389_fu_490;
reg    ap_predicate_pred841_state3;
reg   [31:0] shl_i_i_i_i65391_fu_494;
reg    ap_predicate_pred850_state3;
reg   [31:0] shl_i_i_i_i65393_fu_498;
reg    ap_predicate_pred859_state3;
reg   [31:0] shl_i_i_i_i65395_fu_502;
reg    ap_predicate_pred868_state3;
reg   [31:0] shl_i_i_i_i65397_fu_506;
reg    ap_predicate_pred877_state3;
reg   [31:0] shl_i_i_i_i65399_fu_510;
reg    ap_predicate_pred886_state3;
reg   [31:0] shl_i_i_i_i653101_fu_514;
reg    ap_predicate_pred895_state3;
reg   [31:0] shl_i_i_i_i653103_fu_518;
reg    ap_predicate_pred904_state3;
reg   [31:0] shl_i_i_i_i653105_fu_522;
reg    ap_predicate_pred913_state3;
reg   [31:0] shl_i_i_i_i653107_fu_526;
reg    ap_predicate_pred922_state3;
reg   [31:0] shl_i_i_i_i653109_fu_530;
reg    ap_predicate_pred931_state3;
reg   [31:0] shl_i_i_i_i653111_fu_534;
reg    ap_predicate_pred940_state3;
reg   [31:0] shl_i_i_i_i653113_fu_538;
reg    ap_predicate_pred949_state3;
reg   [31:0] shl_i_i_i_i653115_fu_542;
reg    ap_predicate_pred958_state3;
reg   [31:0] shl_i_i_i_i653117_fu_546;
reg    ap_predicate_pred967_state3;
reg   [31:0] shl_i_i_i_i653119_fu_550;
reg    ap_predicate_pred976_state3;
reg   [31:0] shl_i_i_i_i653121_fu_554;
reg    ap_predicate_pred985_state3;
reg   [31:0] shl_i_i_i_i653123_fu_558;
reg    ap_predicate_pred994_state3;
reg   [31:0] shl_i_i_i_i653125_fu_562;
reg    ap_predicate_pred1003_state3;
reg   [31:0] shl_i_i_i_i653127_fu_566;
reg    ap_predicate_pred1012_state3;
wire    ap_block_pp0_stage0_01001;
reg    layer2_activations_ce0_local;
reg    layer2_activations_1_ce0_local;
reg    layer2_activations_2_ce0_local;
reg    layer2_activations_3_ce0_local;
wire   [3:0] lshr_ln3_fu_1098_p4;
wire   [31:0] x_fu_1121_p9;
wire   [31:0] x_fu_1121_p11;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] x_fu_1121_p1;
wire   [1:0] x_fu_1121_p3;
wire  signed [1:0] x_fu_1121_p5;
wire  signed [1:0] x_fu_1121_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_310 = 7'd0;
#0 shl_i_i_i_i6531_fu_314 = 32'd0;
#0 shl_i_i_i_i6533_fu_318 = 32'd0;
#0 shl_i_i_i_i6535_fu_322 = 32'd0;
#0 shl_i_i_i_i6537_fu_326 = 32'd0;
#0 shl_i_i_i_i6539_fu_330 = 32'd0;
#0 shl_i_i_i_i65311_fu_334 = 32'd0;
#0 shl_i_i_i_i65313_fu_338 = 32'd0;
#0 shl_i_i_i_i65315_fu_342 = 32'd0;
#0 shl_i_i_i_i65317_fu_346 = 32'd0;
#0 shl_i_i_i_i65319_fu_350 = 32'd0;
#0 shl_i_i_i_i65321_fu_354 = 32'd0;
#0 shl_i_i_i_i65323_fu_358 = 32'd0;
#0 shl_i_i_i_i65325_fu_362 = 32'd0;
#0 shl_i_i_i_i65327_fu_366 = 32'd0;
#0 shl_i_i_i_i65329_fu_370 = 32'd0;
#0 shl_i_i_i_i65331_fu_374 = 32'd0;
#0 shl_i_i_i_i65333_fu_378 = 32'd0;
#0 shl_i_i_i_i65335_fu_382 = 32'd0;
#0 shl_i_i_i_i65337_fu_386 = 32'd0;
#0 shl_i_i_i_i65339_fu_390 = 32'd0;
#0 shl_i_i_i_i65341_fu_394 = 32'd0;
#0 shl_i_i_i_i65343_fu_398 = 32'd0;
#0 shl_i_i_i_i65345_fu_402 = 32'd0;
#0 shl_i_i_i_i65347_fu_406 = 32'd0;
#0 shl_i_i_i_i65349_fu_410 = 32'd0;
#0 shl_i_i_i_i65351_fu_414 = 32'd0;
#0 shl_i_i_i_i65353_fu_418 = 32'd0;
#0 shl_i_i_i_i65355_fu_422 = 32'd0;
#0 shl_i_i_i_i65357_fu_426 = 32'd0;
#0 shl_i_i_i_i65359_fu_430 = 32'd0;
#0 shl_i_i_i_i65361_fu_434 = 32'd0;
#0 shl_i_i_i_i65363_fu_438 = 32'd0;
#0 shl_i_i_i_i65365_fu_442 = 32'd0;
#0 shl_i_i_i_i65367_fu_446 = 32'd0;
#0 shl_i_i_i_i65369_fu_450 = 32'd0;
#0 shl_i_i_i_i65371_fu_454 = 32'd0;
#0 shl_i_i_i_i65373_fu_458 = 32'd0;
#0 shl_i_i_i_i65375_fu_462 = 32'd0;
#0 shl_i_i_i_i65377_fu_466 = 32'd0;
#0 shl_i_i_i_i65379_fu_470 = 32'd0;
#0 shl_i_i_i_i65381_fu_474 = 32'd0;
#0 shl_i_i_i_i65383_fu_478 = 32'd0;
#0 shl_i_i_i_i65385_fu_482 = 32'd0;
#0 shl_i_i_i_i65387_fu_486 = 32'd0;
#0 shl_i_i_i_i65389_fu_490 = 32'd0;
#0 shl_i_i_i_i65391_fu_494 = 32'd0;
#0 shl_i_i_i_i65393_fu_498 = 32'd0;
#0 shl_i_i_i_i65395_fu_502 = 32'd0;
#0 shl_i_i_i_i65397_fu_506 = 32'd0;
#0 shl_i_i_i_i65399_fu_510 = 32'd0;
#0 shl_i_i_i_i653101_fu_514 = 32'd0;
#0 shl_i_i_i_i653103_fu_518 = 32'd0;
#0 shl_i_i_i_i653105_fu_522 = 32'd0;
#0 shl_i_i_i_i653107_fu_526 = 32'd0;
#0 shl_i_i_i_i653109_fu_530 = 32'd0;
#0 shl_i_i_i_i653111_fu_534 = 32'd0;
#0 shl_i_i_i_i653113_fu_538 = 32'd0;
#0 shl_i_i_i_i653115_fu_542 = 32'd0;
#0 shl_i_i_i_i653117_fu_546 = 32'd0;
#0 shl_i_i_i_i653119_fu_550 = 32'd0;
#0 shl_i_i_i_i653121_fu_554 = 32'd0;
#0 shl_i_i_i_i653123_fu_558 = 32'd0;
#0 shl_i_i_i_i653125_fu_562 = 32'd0;
#0 shl_i_i_i_i653127_fu_566 = 32'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) feedforward_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U1854(
    .din0(layer2_activations_q0),
    .din1(layer2_activations_1_q0),
    .din2(layer2_activations_2_q0),
    .din3(layer2_activations_3_q0),
    .def(x_fu_1121_p9),
    .sel(trunc_ln153_reg_2128),
    .dout(x_fu_1121_p11)
);

feedforward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln153_fu_1078_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_310 <= add_ln153_fu_1084_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_310 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_predicate_pred1003_state3 <= (trunc_ln153_1_reg_2133 == 6'd0);
        ap_predicate_pred1012_state3 <= (trunc_ln153_1_reg_2133 == 6'd63);
        ap_predicate_pred439_state3 <= (trunc_ln153_1_reg_2133 == 6'd62);
        ap_predicate_pred454_state3 <= (trunc_ln153_1_reg_2133 == 6'd61);
        ap_predicate_pred463_state3 <= (trunc_ln153_1_reg_2133 == 6'd60);
        ap_predicate_pred472_state3 <= (trunc_ln153_1_reg_2133 == 6'd59);
        ap_predicate_pred481_state3 <= (trunc_ln153_1_reg_2133 == 6'd58);
        ap_predicate_pred490_state3 <= (trunc_ln153_1_reg_2133 == 6'd57);
        ap_predicate_pred499_state3 <= (trunc_ln153_1_reg_2133 == 6'd56);
        ap_predicate_pred508_state3 <= (trunc_ln153_1_reg_2133 == 6'd55);
        ap_predicate_pred517_state3 <= (trunc_ln153_1_reg_2133 == 6'd54);
        ap_predicate_pred526_state3 <= (trunc_ln153_1_reg_2133 == 6'd53);
        ap_predicate_pred535_state3 <= (trunc_ln153_1_reg_2133 == 6'd52);
        ap_predicate_pred544_state3 <= (trunc_ln153_1_reg_2133 == 6'd51);
        ap_predicate_pred553_state3 <= (trunc_ln153_1_reg_2133 == 6'd50);
        ap_predicate_pred562_state3 <= (trunc_ln153_1_reg_2133 == 6'd49);
        ap_predicate_pred571_state3 <= (trunc_ln153_1_reg_2133 == 6'd48);
        ap_predicate_pred580_state3 <= (trunc_ln153_1_reg_2133 == 6'd47);
        ap_predicate_pred589_state3 <= (trunc_ln153_1_reg_2133 == 6'd46);
        ap_predicate_pred598_state3 <= (trunc_ln153_1_reg_2133 == 6'd45);
        ap_predicate_pred607_state3 <= (trunc_ln153_1_reg_2133 == 6'd44);
        ap_predicate_pred616_state3 <= (trunc_ln153_1_reg_2133 == 6'd43);
        ap_predicate_pred625_state3 <= (trunc_ln153_1_reg_2133 == 6'd42);
        ap_predicate_pred634_state3 <= (trunc_ln153_1_reg_2133 == 6'd41);
        ap_predicate_pred643_state3 <= (trunc_ln153_1_reg_2133 == 6'd40);
        ap_predicate_pred652_state3 <= (trunc_ln153_1_reg_2133 == 6'd39);
        ap_predicate_pred661_state3 <= (trunc_ln153_1_reg_2133 == 6'd38);
        ap_predicate_pred670_state3 <= (trunc_ln153_1_reg_2133 == 6'd37);
        ap_predicate_pred679_state3 <= (trunc_ln153_1_reg_2133 == 6'd36);
        ap_predicate_pred688_state3 <= (trunc_ln153_1_reg_2133 == 6'd35);
        ap_predicate_pred697_state3 <= (trunc_ln153_1_reg_2133 == 6'd34);
        ap_predicate_pred706_state3 <= (trunc_ln153_1_reg_2133 == 6'd33);
        ap_predicate_pred715_state3 <= (trunc_ln153_1_reg_2133 == 6'd32);
        ap_predicate_pred724_state3 <= (trunc_ln153_1_reg_2133 == 6'd31);
        ap_predicate_pred733_state3 <= (trunc_ln153_1_reg_2133 == 6'd30);
        ap_predicate_pred742_state3 <= (trunc_ln153_1_reg_2133 == 6'd29);
        ap_predicate_pred751_state3 <= (trunc_ln153_1_reg_2133 == 6'd28);
        ap_predicate_pred760_state3 <= (trunc_ln153_1_reg_2133 == 6'd27);
        ap_predicate_pred769_state3 <= (trunc_ln153_1_reg_2133 == 6'd26);
        ap_predicate_pred778_state3 <= (trunc_ln153_1_reg_2133 == 6'd25);
        ap_predicate_pred787_state3 <= (trunc_ln153_1_reg_2133 == 6'd24);
        ap_predicate_pred796_state3 <= (trunc_ln153_1_reg_2133 == 6'd23);
        ap_predicate_pred805_state3 <= (trunc_ln153_1_reg_2133 == 6'd22);
        ap_predicate_pred814_state3 <= (trunc_ln153_1_reg_2133 == 6'd21);
        ap_predicate_pred823_state3 <= (trunc_ln153_1_reg_2133 == 6'd20);
        ap_predicate_pred832_state3 <= (trunc_ln153_1_reg_2133 == 6'd19);
        ap_predicate_pred841_state3 <= (trunc_ln153_1_reg_2133 == 6'd18);
        ap_predicate_pred850_state3 <= (trunc_ln153_1_reg_2133 == 6'd17);
        ap_predicate_pred859_state3 <= (trunc_ln153_1_reg_2133 == 6'd16);
        ap_predicate_pred868_state3 <= (trunc_ln153_1_reg_2133 == 6'd15);
        ap_predicate_pred877_state3 <= (trunc_ln153_1_reg_2133 == 6'd14);
        ap_predicate_pred886_state3 <= (trunc_ln153_1_reg_2133 == 6'd13);
        ap_predicate_pred895_state3 <= (trunc_ln153_1_reg_2133 == 6'd12);
        ap_predicate_pred904_state3 <= (trunc_ln153_1_reg_2133 == 6'd11);
        ap_predicate_pred913_state3 <= (trunc_ln153_1_reg_2133 == 6'd10);
        ap_predicate_pred922_state3 <= (trunc_ln153_1_reg_2133 == 6'd9);
        ap_predicate_pred931_state3 <= (trunc_ln153_1_reg_2133 == 6'd8);
        ap_predicate_pred940_state3 <= (trunc_ln153_1_reg_2133 == 6'd7);
        ap_predicate_pred949_state3 <= (trunc_ln153_1_reg_2133 == 6'd6);
        ap_predicate_pred958_state3 <= (trunc_ln153_1_reg_2133 == 6'd5);
        ap_predicate_pred967_state3 <= (trunc_ln153_1_reg_2133 == 6'd4);
        ap_predicate_pred976_state3 <= (trunc_ln153_1_reg_2133 == 6'd3);
        ap_predicate_pred985_state3 <= (trunc_ln153_1_reg_2133 == 6'd2);
        ap_predicate_pred994_state3 <= (trunc_ln153_1_reg_2133 == 6'd1);
        icmp_ln153_reg_2124 <= icmp_ln153_fu_1078_p2;
        icmp_ln41_reg_2157 <= icmp_ln41_fu_1144_p2;
        trunc_ln153_1_reg_2133 <= trunc_ln153_1_fu_1094_p1;
        trunc_ln153_reg_2128 <= trunc_ln153_fu_1090_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred895_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653101_fu_514[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred904_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653103_fu_518[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred913_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653105_fu_522[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred922_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653107_fu_526[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred931_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653109_fu_530[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred940_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653111_fu_534[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred949_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653113_fu_538[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred958_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653115_fu_542[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred967_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653117_fu_546[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred976_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653119_fu_550[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred490_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65311_fu_334[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred985_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653121_fu_554[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred994_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i653123_fu_558[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1003_state3 == 1'b1))) begin
        shl_i_i_i_i653125_fu_562[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_predicate_pred1012_state3 == 1'b1))) begin
        shl_i_i_i_i653127_fu_566[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred499_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65313_fu_338[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred508_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65315_fu_342[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred517_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65317_fu_346[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred526_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65319_fu_350[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred439_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i6531_fu_314[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred535_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65321_fu_354[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred544_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65323_fu_358[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred553_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65325_fu_362[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred562_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65327_fu_366[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred571_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65329_fu_370[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred580_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65331_fu_374[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred589_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65333_fu_378[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred598_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65335_fu_382[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred607_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65337_fu_386[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred616_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65339_fu_390[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred454_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i6533_fu_318[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred625_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65341_fu_394[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred634_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65343_fu_398[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred643_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65345_fu_402[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred652_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65347_fu_406[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred661_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65349_fu_410[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred670_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65351_fu_414[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred679_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65353_fu_418[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred688_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65355_fu_422[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred697_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65357_fu_426[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred706_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65359_fu_430[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred463_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i6535_fu_322[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred715_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65361_fu_434[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred724_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65363_fu_438[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred733_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65365_fu_442[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred742_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65367_fu_446[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred751_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65369_fu_450[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred760_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65371_fu_454[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred769_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65373_fu_458[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred778_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65375_fu_462[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred787_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65377_fu_466[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred796_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65379_fu_470[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred472_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i6537_fu_326[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred805_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65381_fu_474[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred814_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65383_fu_478[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred823_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65385_fu_482[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred832_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65387_fu_486[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred841_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65389_fu_490[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred850_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65391_fu_494[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred859_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65393_fu_498[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred868_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65395_fu_502[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred877_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65397_fu_506[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred886_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i65399_fu_510[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_pred481_state3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        shl_i_i_i_i6539_fu_330[8] <= select_ln156_fu_1150_p3[8];
    end
end

always @ (*) begin
    if (((icmp_ln153_fu_1078_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_3 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_310;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_activations_1_ce0_local = 1'b1;
    end else begin
        layer2_activations_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_activations_2_ce0_local = 1'b1;
    end else begin
        layer2_activations_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_activations_3_ce0_local = 1'b1;
    end else begin
        layer2_activations_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer2_activations_ce0_local = 1'b1;
    end else begin
        layer2_activations_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653101_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653101_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653103_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653103_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653105_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653105_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653107_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653107_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653109_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653109_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653111_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653111_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653113_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653113_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653115_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653115_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653117_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653117_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653119_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653119_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65311_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65311_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653121_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653121_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653123_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653123_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653125_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653125_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i653127_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i653127_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65313_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65313_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65315_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65315_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65317_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65317_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65319_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65319_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i6531_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i6531_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65321_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65321_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65323_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65323_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65325_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65325_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65327_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65327_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65329_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65329_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65331_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65331_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65333_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65333_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65335_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65335_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65337_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65337_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65339_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65339_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i6533_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i6533_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65341_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65341_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65343_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65343_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65345_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65345_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65347_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65347_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65349_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65349_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65351_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65351_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65353_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65353_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65355_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65355_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65357_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65357_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65359_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65359_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i6535_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i6535_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65361_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65361_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65363_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65363_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65365_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65365_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65367_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65367_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65369_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65369_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65371_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65371_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65373_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65373_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65375_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65375_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65377_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65377_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65379_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65379_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i6537_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i6537_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65381_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65381_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65383_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65383_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65385_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65385_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65387_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65387_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65389_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65389_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65391_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65391_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65393_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65393_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65395_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65395_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65397_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65397_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i65399_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i65399_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln153_reg_2124 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        shl_i_i_i_i6539_out_ap_vld = 1'b1;
    end else begin
        shl_i_i_i_i6539_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln153_fu_1084_p2 = (ap_sig_allocacmp_i_3 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln153_fu_1078_p2 = ((ap_sig_allocacmp_i_3 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_1144_p2 = (($signed(x_fu_1121_p11) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign layer2_activations_1_address0 = zext_ln153_fu_1108_p1;

assign layer2_activations_1_ce0 = layer2_activations_1_ce0_local;

assign layer2_activations_2_address0 = zext_ln153_fu_1108_p1;

assign layer2_activations_2_ce0 = layer2_activations_2_ce0_local;

assign layer2_activations_3_address0 = zext_ln153_fu_1108_p1;

assign layer2_activations_3_ce0 = layer2_activations_3_ce0_local;

assign layer2_activations_address0 = zext_ln153_fu_1108_p1;

assign layer2_activations_ce0 = layer2_activations_ce0_local;

assign lshr_ln3_fu_1098_p4 = {{ap_sig_allocacmp_i_3[5:2]}};

assign select_ln156_fu_1150_p3 = ((icmp_ln41_reg_2157[0:0] == 1'b1) ? 32'd0 : 32'd256);

assign shl_i_i_i_i653101_out = shl_i_i_i_i653101_fu_514;

assign shl_i_i_i_i653103_out = shl_i_i_i_i653103_fu_518;

assign shl_i_i_i_i653105_out = shl_i_i_i_i653105_fu_522;

assign shl_i_i_i_i653107_out = shl_i_i_i_i653107_fu_526;

assign shl_i_i_i_i653109_out = shl_i_i_i_i653109_fu_530;

assign shl_i_i_i_i653111_out = shl_i_i_i_i653111_fu_534;

assign shl_i_i_i_i653113_out = shl_i_i_i_i653113_fu_538;

assign shl_i_i_i_i653115_out = shl_i_i_i_i653115_fu_542;

assign shl_i_i_i_i653117_out = shl_i_i_i_i653117_fu_546;

assign shl_i_i_i_i653119_out = shl_i_i_i_i653119_fu_550;

assign shl_i_i_i_i65311_out = shl_i_i_i_i65311_fu_334;

assign shl_i_i_i_i653121_out = shl_i_i_i_i653121_fu_554;

assign shl_i_i_i_i653123_out = shl_i_i_i_i653123_fu_558;

assign shl_i_i_i_i653125_out = shl_i_i_i_i653125_fu_562;

assign shl_i_i_i_i653127_out = shl_i_i_i_i653127_fu_566;

assign shl_i_i_i_i65313_out = shl_i_i_i_i65313_fu_338;

assign shl_i_i_i_i65315_out = shl_i_i_i_i65315_fu_342;

assign shl_i_i_i_i65317_out = shl_i_i_i_i65317_fu_346;

assign shl_i_i_i_i65319_out = shl_i_i_i_i65319_fu_350;

assign shl_i_i_i_i6531_out = shl_i_i_i_i6531_fu_314;

assign shl_i_i_i_i65321_out = shl_i_i_i_i65321_fu_354;

assign shl_i_i_i_i65323_out = shl_i_i_i_i65323_fu_358;

assign shl_i_i_i_i65325_out = shl_i_i_i_i65325_fu_362;

assign shl_i_i_i_i65327_out = shl_i_i_i_i65327_fu_366;

assign shl_i_i_i_i65329_out = shl_i_i_i_i65329_fu_370;

assign shl_i_i_i_i65331_out = shl_i_i_i_i65331_fu_374;

assign shl_i_i_i_i65333_out = shl_i_i_i_i65333_fu_378;

assign shl_i_i_i_i65335_out = shl_i_i_i_i65335_fu_382;

assign shl_i_i_i_i65337_out = shl_i_i_i_i65337_fu_386;

assign shl_i_i_i_i65339_out = shl_i_i_i_i65339_fu_390;

assign shl_i_i_i_i6533_out = shl_i_i_i_i6533_fu_318;

assign shl_i_i_i_i65341_out = shl_i_i_i_i65341_fu_394;

assign shl_i_i_i_i65343_out = shl_i_i_i_i65343_fu_398;

assign shl_i_i_i_i65345_out = shl_i_i_i_i65345_fu_402;

assign shl_i_i_i_i65347_out = shl_i_i_i_i65347_fu_406;

assign shl_i_i_i_i65349_out = shl_i_i_i_i65349_fu_410;

assign shl_i_i_i_i65351_out = shl_i_i_i_i65351_fu_414;

assign shl_i_i_i_i65353_out = shl_i_i_i_i65353_fu_418;

assign shl_i_i_i_i65355_out = shl_i_i_i_i65355_fu_422;

assign shl_i_i_i_i65357_out = shl_i_i_i_i65357_fu_426;

assign shl_i_i_i_i65359_out = shl_i_i_i_i65359_fu_430;

assign shl_i_i_i_i6535_out = shl_i_i_i_i6535_fu_322;

assign shl_i_i_i_i65361_out = shl_i_i_i_i65361_fu_434;

assign shl_i_i_i_i65363_out = shl_i_i_i_i65363_fu_438;

assign shl_i_i_i_i65365_out = shl_i_i_i_i65365_fu_442;

assign shl_i_i_i_i65367_out = shl_i_i_i_i65367_fu_446;

assign shl_i_i_i_i65369_out = shl_i_i_i_i65369_fu_450;

assign shl_i_i_i_i65371_out = shl_i_i_i_i65371_fu_454;

assign shl_i_i_i_i65373_out = shl_i_i_i_i65373_fu_458;

assign shl_i_i_i_i65375_out = shl_i_i_i_i65375_fu_462;

assign shl_i_i_i_i65377_out = shl_i_i_i_i65377_fu_466;

assign shl_i_i_i_i65379_out = shl_i_i_i_i65379_fu_470;

assign shl_i_i_i_i6537_out = shl_i_i_i_i6537_fu_326;

assign shl_i_i_i_i65381_out = shl_i_i_i_i65381_fu_474;

assign shl_i_i_i_i65383_out = shl_i_i_i_i65383_fu_478;

assign shl_i_i_i_i65385_out = shl_i_i_i_i65385_fu_482;

assign shl_i_i_i_i65387_out = shl_i_i_i_i65387_fu_486;

assign shl_i_i_i_i65389_out = shl_i_i_i_i65389_fu_490;

assign shl_i_i_i_i65391_out = shl_i_i_i_i65391_fu_494;

assign shl_i_i_i_i65393_out = shl_i_i_i_i65393_fu_498;

assign shl_i_i_i_i65395_out = shl_i_i_i_i65395_fu_502;

assign shl_i_i_i_i65397_out = shl_i_i_i_i65397_fu_506;

assign shl_i_i_i_i65399_out = shl_i_i_i_i65399_fu_510;

assign shl_i_i_i_i6539_out = shl_i_i_i_i6539_fu_330;

assign trunc_ln153_1_fu_1094_p1 = ap_sig_allocacmp_i_3[5:0];

assign trunc_ln153_fu_1090_p1 = ap_sig_allocacmp_i_3[1:0];

assign x_fu_1121_p9 = 'bx;

assign zext_ln153_fu_1108_p1 = lshr_ln3_fu_1098_p4;

always @ (posedge ap_clk) begin
    shl_i_i_i_i6531_fu_314[7:0] <= 8'b00000000;
    shl_i_i_i_i6531_fu_314[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i6533_fu_318[7:0] <= 8'b00000000;
    shl_i_i_i_i6533_fu_318[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i6535_fu_322[7:0] <= 8'b00000000;
    shl_i_i_i_i6535_fu_322[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i6537_fu_326[7:0] <= 8'b00000000;
    shl_i_i_i_i6537_fu_326[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i6539_fu_330[7:0] <= 8'b00000000;
    shl_i_i_i_i6539_fu_330[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65311_fu_334[7:0] <= 8'b00000000;
    shl_i_i_i_i65311_fu_334[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65313_fu_338[7:0] <= 8'b00000000;
    shl_i_i_i_i65313_fu_338[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65315_fu_342[7:0] <= 8'b00000000;
    shl_i_i_i_i65315_fu_342[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65317_fu_346[7:0] <= 8'b00000000;
    shl_i_i_i_i65317_fu_346[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65319_fu_350[7:0] <= 8'b00000000;
    shl_i_i_i_i65319_fu_350[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65321_fu_354[7:0] <= 8'b00000000;
    shl_i_i_i_i65321_fu_354[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65323_fu_358[7:0] <= 8'b00000000;
    shl_i_i_i_i65323_fu_358[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65325_fu_362[7:0] <= 8'b00000000;
    shl_i_i_i_i65325_fu_362[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65327_fu_366[7:0] <= 8'b00000000;
    shl_i_i_i_i65327_fu_366[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65329_fu_370[7:0] <= 8'b00000000;
    shl_i_i_i_i65329_fu_370[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65331_fu_374[7:0] <= 8'b00000000;
    shl_i_i_i_i65331_fu_374[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65333_fu_378[7:0] <= 8'b00000000;
    shl_i_i_i_i65333_fu_378[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65335_fu_382[7:0] <= 8'b00000000;
    shl_i_i_i_i65335_fu_382[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65337_fu_386[7:0] <= 8'b00000000;
    shl_i_i_i_i65337_fu_386[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65339_fu_390[7:0] <= 8'b00000000;
    shl_i_i_i_i65339_fu_390[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65341_fu_394[7:0] <= 8'b00000000;
    shl_i_i_i_i65341_fu_394[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65343_fu_398[7:0] <= 8'b00000000;
    shl_i_i_i_i65343_fu_398[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65345_fu_402[7:0] <= 8'b00000000;
    shl_i_i_i_i65345_fu_402[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65347_fu_406[7:0] <= 8'b00000000;
    shl_i_i_i_i65347_fu_406[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65349_fu_410[7:0] <= 8'b00000000;
    shl_i_i_i_i65349_fu_410[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65351_fu_414[7:0] <= 8'b00000000;
    shl_i_i_i_i65351_fu_414[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65353_fu_418[7:0] <= 8'b00000000;
    shl_i_i_i_i65353_fu_418[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65355_fu_422[7:0] <= 8'b00000000;
    shl_i_i_i_i65355_fu_422[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65357_fu_426[7:0] <= 8'b00000000;
    shl_i_i_i_i65357_fu_426[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65359_fu_430[7:0] <= 8'b00000000;
    shl_i_i_i_i65359_fu_430[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65361_fu_434[7:0] <= 8'b00000000;
    shl_i_i_i_i65361_fu_434[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65363_fu_438[7:0] <= 8'b00000000;
    shl_i_i_i_i65363_fu_438[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65365_fu_442[7:0] <= 8'b00000000;
    shl_i_i_i_i65365_fu_442[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65367_fu_446[7:0] <= 8'b00000000;
    shl_i_i_i_i65367_fu_446[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65369_fu_450[7:0] <= 8'b00000000;
    shl_i_i_i_i65369_fu_450[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65371_fu_454[7:0] <= 8'b00000000;
    shl_i_i_i_i65371_fu_454[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65373_fu_458[7:0] <= 8'b00000000;
    shl_i_i_i_i65373_fu_458[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65375_fu_462[7:0] <= 8'b00000000;
    shl_i_i_i_i65375_fu_462[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65377_fu_466[7:0] <= 8'b00000000;
    shl_i_i_i_i65377_fu_466[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65379_fu_470[7:0] <= 8'b00000000;
    shl_i_i_i_i65379_fu_470[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65381_fu_474[7:0] <= 8'b00000000;
    shl_i_i_i_i65381_fu_474[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65383_fu_478[7:0] <= 8'b00000000;
    shl_i_i_i_i65383_fu_478[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65385_fu_482[7:0] <= 8'b00000000;
    shl_i_i_i_i65385_fu_482[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65387_fu_486[7:0] <= 8'b00000000;
    shl_i_i_i_i65387_fu_486[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65389_fu_490[7:0] <= 8'b00000000;
    shl_i_i_i_i65389_fu_490[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65391_fu_494[7:0] <= 8'b00000000;
    shl_i_i_i_i65391_fu_494[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65393_fu_498[7:0] <= 8'b00000000;
    shl_i_i_i_i65393_fu_498[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65395_fu_502[7:0] <= 8'b00000000;
    shl_i_i_i_i65395_fu_502[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65397_fu_506[7:0] <= 8'b00000000;
    shl_i_i_i_i65397_fu_506[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i65399_fu_510[7:0] <= 8'b00000000;
    shl_i_i_i_i65399_fu_510[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653101_fu_514[7:0] <= 8'b00000000;
    shl_i_i_i_i653101_fu_514[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653103_fu_518[7:0] <= 8'b00000000;
    shl_i_i_i_i653103_fu_518[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653105_fu_522[7:0] <= 8'b00000000;
    shl_i_i_i_i653105_fu_522[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653107_fu_526[7:0] <= 8'b00000000;
    shl_i_i_i_i653107_fu_526[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653109_fu_530[7:0] <= 8'b00000000;
    shl_i_i_i_i653109_fu_530[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653111_fu_534[7:0] <= 8'b00000000;
    shl_i_i_i_i653111_fu_534[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653113_fu_538[7:0] <= 8'b00000000;
    shl_i_i_i_i653113_fu_538[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653115_fu_542[7:0] <= 8'b00000000;
    shl_i_i_i_i653115_fu_542[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653117_fu_546[7:0] <= 8'b00000000;
    shl_i_i_i_i653117_fu_546[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653119_fu_550[7:0] <= 8'b00000000;
    shl_i_i_i_i653119_fu_550[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653121_fu_554[7:0] <= 8'b00000000;
    shl_i_i_i_i653121_fu_554[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653123_fu_558[7:0] <= 8'b00000000;
    shl_i_i_i_i653123_fu_558[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653125_fu_562[7:0] <= 8'b00000000;
    shl_i_i_i_i653125_fu_562[31:9] <= 23'b00000000000000000000000;
    shl_i_i_i_i653127_fu_566[7:0] <= 8'b00000000;
    shl_i_i_i_i653127_fu_566[31:9] <= 23'b00000000000000000000000;
end

endmodule //feedforward_feedforward_Pipeline_VITIS_LOOP_153_5
